server:
  port: 12000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JackySharp/tensquare-configfile.git  #存放yml文件的远程仓库地址
  rabbitmq:
    host: 192.168.25.130
management:  #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh